### PR TITLE
Fix bad file descriptor crashes

### LINKED ISSUE #76: Random Runner Crashes After Upgrading to 0.8
We recently upgraded to Tartelet 0.8, and since then, we've been experiencing random crashes of our runners. This issue is impacting our CI/CD workflow, and we're trying to identify the cause.

We are now using Tartelet version 0.8.3, tart version 2.9.0, and are using the xcode 15.3 image from [cirruslabs](https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-sonoma-xcode/200884874?tag=15.3) and the host is running sonoma 14.4.1.

This is how the VM's look when connection to the host:
Screenshot 2024-04-17 at 12 57 20

We are unsure whether this problem is related to Tartelet itself, the underlying Tart tool, the VM image, or our GitHub Actions job. Has anyone else experienced similar issues after upgrading? Any insights or suggestions would be greatly appreciated.

Thank you for your assistance!

### LINKED ISSUE #93: Sporadic crashes
### What happened?

Tartelet is crashing for me on my CI boxes.

### What are the steps to reproduce?

There's no way to reliably reproduce the issue, but it happens at least once a day.

Here is the crash report: 

[Tartelet-2024-09-04-181504.ips.zip](https://github.com/user-attachments/files/16929474/Tartelet-2024-09-04-181504.ips.zip)

### What is the expected behavior?

Tartlet doesn't crash.

### PR DESCRIPTION
**Pull request by kuhnroyal**
## Description
Explicitly close the pipe file handle after the data has been read.

## Motivation and Context
Fixes #93 
Fixes #76 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by tonyarnold — APPROVED** [review]

**Comment by kuhnroyal** [comment]
@simonbs Can you please check this and approve the workflow when you get a chance?

**Review by simonbs — APPROVED** [review]

**Comment by simonbs** [comment]
Looks great! Thanks for contributing these changes! 🙏

**Comment by kuhnroyal** [comment]
I am not very familiar with Swift, any tips how to handle potential error here as the force try is a lint error.

**Comment by simonbs** [comment]
@kuhnroyal No worries. I've pushed some changes that should address it.

**Comment by simonbs** [comment]
This is included [in 0.10.1 which was just published](https://github.com/shapehq/tartelet/releases/tag/0.10.1).

**Pull request merged**
